name: Release
on:
  push:
    branch:
      build
  workflow_dispatch:

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      
      - name: Node.js setup
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: Install app dependencies and build web
        run: yarn

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
      
      - name: Push windows binaries to bin repository
        if: matrix.platform == 'windows-latest'
        run: |
          git config user.name "FtcSerhiy"
          git config user.email "ftcserhiy@gmail.com"
          git checkout -b bin
          mv src-tauri/target/release/*.exe .
          git add .
          git commit -m "add binaries"
          git push -uf origin bin
        env:
          TOKEN: ${{ secrets.TOKEN }}


